### ISSUE TITLE
function

### ISSUE THREAD

**Issue by Braziken** [Mahesh0253/Media-Search-bot#1]
Put a function so that it reads the old posts from my channel and index

**Comment by Mahesh0253** [comment]
I was trying, but bots can't iter chat history so it is not possible as now

**Comment by SpEcHiDe** [comment]
how about a one time user that indexes old posts,? 😬🤔🤔🤪

**Comment by mesele16** [comment]
Could you please add Subscription checking for new users to check Whether they have joined my channel or not if not they have to join if not they will not use the bot till they join 
![IMG_20201002_130458_066](https://user-images.githubusercontent.com/55573093/94912164-eacca480-04af-11eb-855b-20ea2aeabeec.jpg)

**Comment by Mahesh0253** [comment]
> Put a function so that it reads the old posts from my channel and index

Run [one_time_indexer.py](https://github.com/Mahesh0253/Media-Search-bot/blob/master/one_time_indexer.py) file to save old file posts
