### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by X-Gorn** [Mahesh0253/Media-Search-bot#10]
Make it able to Search Files by the Caption

**Comment by Mahesh0253** [comment]
Replace [utils.py line 69](https://github.com/Mahesh0253/Media-Search-bot/blob/ac3c3afee3e0343bcc97ad29b05126a93670a2ad/utils.py#L69) by `filter = {'$or': [{'file_name': regex}, {'caption': regex}]}`
