### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Nksama** [Mahesh0253/Media-Search-bot#25]
this repo is not working it only shows messgae in bot but not files

**Comment by Mahesh0253** [comment]
Watch video tutorial and follow steps -
https://youtu.be/dsuTn4qV2GA

**Comment by Nksama** [comment]
Seem only showing no results

**Comment by Clinton-Abraham** [comment]
> not

Enable inline mode

**Comment by Nksama** [comment]
> > not
> 
> Enable inline mode

No
Showing like this for all results
https://telegra.ph/file/f793304de4fea8ca90bc5.jpg

**Comment by Nksama** [comment]
No showing like this for all
https://telegra.ph/file/11a88ace6f6a33a5a7005.jpg

**Comment by Mahesh0253** [comment]
Use `/total` command and checks file are saved or not. If not then check logs
