### ISSUE TITLE
issue when using delete command

### ISSUE THREAD

**Issue by SpEcHiDe** [Mahesh0253/Media-Search-bot#3]
I saw this code, https://github.com/Mahesh0253/Media-Search-bot/blob/master/plugins/commands.py#L76

Steps to reproduce:
1. Add a file to an index. 
2. After 12 hours forward the file from channel, and reply the /delete command
 
Actual Results:
It will reply "File not found in database"

Expected Results:
it should delete the file from the database.

**Comment by Mahesh0253** [comment]
Fixed in [new](https://github.com/Mahesh0253/Media-Search-bot/commit/bbc79bbdbd4df88a775df3d1b8726b5ec76f74be) commit
