### ISSUE TITLE
small size videos are not saveing...

### ISSUE THREAD

**Issue by vishnuprasad0** [Mahesh0253/Media-Search-bot#31]
small size videos are not saveing...Help me to do it

**Comment by vishnuprasad0** [comment]
while senting small videos ( like  10-15 Mb videos ) it's not saving in data base...

**Comment by nikhileashy** [comment]
> while senting small videos ( like 10-15 Mb videos ) it's not saving in data base...

Bro can you please pm me in Telegram @n_a_c_creative
