### ISSUE TITLE
Indexing Error

### ISSUE THREAD

**Issue by Monster-ZeroX** [Mahesh0253/Media-Search-bot#40]
![image](https://user-images.githubusercontent.com/69518719/129434625-638aae91-5ae3-4efb-8e44-3a14368d9630.png)

/index -46464634186

Error Msg

Error: unpack requires a buffer of 263 bytes

**Comment by Monster-ZeroX** [comment]
How Can I Fix This

**Comment by Mahesh0253** [comment]
I think `-46464634186` is wrong chat id

**Comment by Maheshmodi1** [comment]
Error: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")  hello bro please help me with this error

**Comment by Mahesh0253** [comment]
Contact me in [Support group](https://t.me/botxsupport)

**Comment by rk125007** [comment]
Is it support password protected Index ?

**Comment by Mahesh0253** [comment]
> Is it support password protected Index ?

No
